# https://github.com/marketplace/actions/docker-login
name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Configures the node version used on GitHub-hosted runners
      - uses: actions/setup-node
        with:
        # The Node.js version to configure
        node-version: 12
